export {Class} from './Class'
export {MenuPrincipal} from './MenuPrincipal'
export {Messages} from './Messages'
export {Projects} from './Projects'
export {StudentDatas} from './StudentDatas'
export {Login} from './Login'